# Generated by Django 2.2.18 on 2021-02-12 12:53

from django.db import migrations, models
import spectrum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('color', spectrum.fields.ColorField(default='#FFFF00', verbose_name='color')),
            ],
        ),
    ]
