# Generated by Django 2.2.18 on 2021-02-13 16:08

from django.db import migrations
import spectrum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='color',
            field=spectrum.fields.ColorField(blank=True, default='#FFFF00', verbose_name='color'),
        ),
    ]
