# Generated by Django 4.0.4 on 2022-06-08 05:41

from django.db import migrations
import spectrum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='color',
            field=spectrum.fields.ColorField(blank=True, default='#FFFF00', verbose_name='color'),
        ),
    ]
