# Generated by Django 2.1.5 on 2019-01-16 17:05

from django.db import migrations
import spectrum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='color',
            field=spectrum.fields.ColorField(default='#FFFF00', verbose_name='color'),
        ),
    ]
